[project]
name = "mackerel-external-alerts-csv-exporter"
version = "0.1.0"
description = "Mackerelの外形監視のアラートをCSVに出力するスクリプト"
readme = "README.md"
requires-python = ">=3.9"
dependencies = []

[tool.uv]
dev-dependencies = [
    "ruff>=0.6.9",
]
